[package]
name = "horse-racing-duals"
version = "0.1.0"
authors = ["Forrest Stanley <forrest@dihedr.al>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
